spring.application.name=spot-management
# H2データベース設定
spring.datasource.url=jdbc:h2:mem:spotdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2コンソール設定（ブラウザでDBを確認できる）
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA設定
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Thymeleaf設定
spring.thymeleaf.cache=false